title: Product
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: description
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: Description
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
      -
        handle: price
        field:
          input_type: number
          antlers: false
          display: Price
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: compotition
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: Compotition
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
      -
        handle: marketplace
        field:
          mode: dynamic
          display: Marketplace
          type: array
          icon: array
          instructions: 'Isi link produk ini dari marketplace manapun misalnya shopee, tokopedia, bukalapak, dll.'
          listable: hidden
          instructions_position: above
      -
        handle: image
        field:
          mode: list
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Image
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
      -
        handle: template
        field:
          hide_partials: true
          display: Template
          type: template
          icon: template
          listable: hidden
          instructions_position: above
          instructions: 'Pilih template "product/detail"'
          validate:
            - required
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
